import { DataDash } from "./data_dash.slint";
export component SmallGauge {
    in-out property <length> radius;
    in property <int> dashboard_value;
    in property <int> dashboard_max_value;
    in property <int> dashboard_min_value;
    in property <[float]> pointed-values;
    in property <[float]> unpointed-values;
    in property <[float]> red-values;
    in property <[float]> init-values;
    in property <[float]> blue-values;
    in property <color> image-color: white;
    in property <int> start-from-degree;
    in property <int> end-at-degree;
    in property <length> font-size: 9px;
    in property <image> image;
    circle:=Rectangle {
        width: radius;
        height: radius;
        background: black;
        border_radius: radius;
    }
    Rectangle {
        width: radius * 0.15;
        height: radius * 0.15;
        y: circle.y + 42px;
        background: grey;
        border_radius: radius;
    }
    Image {
        source: image;
        width: radius * 0.15;
        height: radius * 0.15;
        x: circle.x + radius / 2 - 5px;
        y: circle.y + radius / 2 - 10px;
        colorize: image-color;
    }
    for i in red-values: DataDash {
        start-from-degree: start-from-degree;
        end-at-degree: end-at-degree;
        x: circle.x;
        y: circle.y;
        radius: radius;
        value: i;
        has-text: false;
        is-red: true;
        max-value: dashboard_max_value;
        min-value: dashboard_min_value;
        transform_origin_x: -circle.x;
        font-size: font-size;
    }
    for i in blue-values: DataDash {
        start-from-degree: start-from-degree;
        end-at-degree: end-at-degree;
        x: circle.x;
        y: circle.y;
        radius: radius;
        value: i;
        has-text: false;
        is-blue: true;
        max_value: dashboard_max_value;
        min_value: dashboard_min_value;
        transform_origin_x: -circle.x;
        font-size: font-size;
    }
    for i in pointed-values: DataDash {
        start-from-degree: start-from-degree;
        end-at-degree: end-at-degree;
        x: circle.x;
        y: circle.y;
        radius: radius;
        value: i;
        big-point: true;
        has-text: true;
        max_value: dashboard_max_value;
        transform_origin_x: -circle.x;
        font-size: font-size;
        min_value: dashboard_min_value;
    }
    for i in init-values: DataDash {
        start-from-degree: start-from-degree;
        end-at-degree: end-at-degree;
        x: circle.x;
        y: circle.y;
        radius: radius;
        value: i;
        big-point: true;
        max_value: dashboard_max_value;
        transform_origin_x: -circle.x;
        font-size: font-size;
        min_value: dashboard_min_value;
    }
    for i in unpointed-values: DataDash {
        start-from-degree: start-from-degree;
        end-at-degree: end-at-degree;
        x: circle.x;
        y: circle.y;
        radius: radius;
        value: i;
        big-point: false;
        has-text: false;
        max_value: dashboard_max_value;
        transform_origin_x: -circle.x;
        font-size: font-size;
        min_value: dashboard_min_value;
    }
    Rectangle {
        width: radius * 0.8;
        height: 1px;
        x: circle.x - radius / 32;
        y: circle.y + radius / 1.5;
        background: white;
        border_radius: 0px;
        transform_rotation: dashboard_value > dashboard_max_value ? (end-at-degree - 15) * 1deg : dashboard_value < dashboard_min_value ? start-from-degree * 1deg + 15deg : start-from-degree * 1deg + 15deg + 1deg * (end-at-degree - start-from-degree - 30) * (dashboard_value - dashboard_min_value) / (dashboard_max_value - dashboard_min_value);
        transform_origin: {x: -self.x, y: 0px};
    }
}